# Backend Dockerfile
FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy backend source
COPY ./backend ./

EXPOSE 5000

CMD [ "node", "server.js" ]
